# Generated by Django 3.1.7 on 2021-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('WatchedMovieId', models.AutoField(primary_key=True, serialize=False)),
                ('WatchedMovieName', models.CharField(max_length=100)),
                ('WatchedRank', models.CharField(max_length=100)),
                ('IMDBRank', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('ShowOrMovie', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ToWatch',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('ShowOrMovie', models.CharField(max_length=5)),
            ],
        ),
    ]
