# Generated by Django 3.1.7 on 2021-03-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='WatchedRank',
            new_name='WatchedRating',
        ),
    ]
