# Generated by Django 3.1.7 on 2021-03-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_remove_towatch_photofilename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towatch',
            old_name='ShowOrMovie',
            new_name='MovieOrShow',
        ),
    ]
